import os, shutil
from ruamel.yaml import YAML
yaml = YAML()

wpt_canvas_directory = "/Users/aaronhk/chrome/src/third_party/blink/web_tests/external/wpt/html/canvas"
IS_OFFSCREEN = False

def is_autogenerated(file): # see if a test at file is autogenerated
  with(open(file, 'r')) as infile:
    lines = infile.readlines()
    for line in lines:
      if line.find("DO NOT EDIT!") != -1:
        return True
  return False

def get_yamls(folder, name=""):
  result = []
  for path, directories, files in os.walk(folder):
    for file in files:
      basename, extension = os.path.splitext(file)
      if extension == ".yml" or extension == ".yaml":
        if basename.find(name) != -1:
          result.append(os.path.join(path, file))
  return(result)

def map_name(name, name_mapping):
  mapped_name = None
  for mn in sorted(name_mapping.keys(), key=len, reverse=True):
    if name.startswith(mn):
      mapped_name = os.path.split(name_mapping[mn])[-1]
      break
  if not mapped_name:
    print("LIKELY ERROR: %s has no defined target directory mapping" % name)
  # if 'manual' in test:
  #   mapped_name += "-manual"
  return mapped_name

meta = []
def get_new_files(template_file, name_mapping_file, new_files):
  with open(template_file, "r") as file:
      templates = yaml.load(file)
  with open(name_mapping_file, "r") as file:
      name_mapping = yaml.load(file)
  for t in templates:
    if 'name' not in t:
      if 'meta' in t:
        meta.append(t)
      else:
        print("Weird entry: {}".format(t))
      continue
    else:
      new_file_name = map_name(t['name'], name_mapping)
      if new_file_name not in new_files:
        print("ADDING {}".format(new_file_name))
        new_files[new_file_name] = []
      new_files[new_file_name].append(t)
      # if t['name'].find("2d.fillStyle.parse.invalid"):
      #   print(t)
  # for n in new_files:
  #   for m in meta:
  #     new_files[n].append(m) # I think we want the metas everywhere?
  return new_files


test_yaml_files = get_yamls(wpt_canvas_directory, "test")
name_2_dir_files = get_yamls(wpt_canvas_directory, "name2dir")

# filter for offscreen
if IS_OFFSCREEN:
  test_yaml_files = [f for f in test_yaml_files if f.find("offscreen") != -1]
  name_2_dir_files = [f for f in name_2_dir_files if f.find("offscreen") != -1]
else:
  test_yaml_files = [f for f in test_yaml_files if f.find("offscreen") == -1]
  name_2_dir_files = [f for f in name_2_dir_files if f.find("offscreen") == -1]

name_2_dir_file = name_2_dir_files[0]
output_folder = "output/element"
if IS_OFFSCREEN:
  output_folder = "output/offscreen"
all_files = {}
for template in test_yaml_files:
  get_new_files(template, name_2_dir_file, all_files)
for file in all_files:
  print(file, template)
    with open("{d}/{f}.yaml".format(d=output_folder, f=file), "w") as outfile:
    yaml.dump(all_files[file], outfile)
with open("{}/meta.yaml".format(output_folder), "w") as outfile:
  yaml.dump(meta, outfile)

